### ISSUE TITLE
`ADD ...` instead of `RUN curl ...`

### ISSUE THREAD

**Issue by ocket8888** [ericchaves/ats-lua-playground#1]
If you use `ADD` to fetch network resources instead of `RUN`ing `curl`, you can get Docker to cache that step based on ETag/If-Modified-Since headers. Otherwise it just always assumes it's up-to-date as long as previous commands/dependent arguments are run/changed. That means you can have a cache layer for each version independently, whereas right now I believe it would fetch the source tarball every time you change versions - regardless of whether or not it has a cache layer for that version already. Could save some time.

**Comment by ericchaves** [comment]
Hi @ocket8888, thanks for the suggestion. I avoided the ADD to follow [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy):
> Because image size matters, using ADD to fetch packages from remote URLs is strongly discouraged; 

Since I don't rebuild so often it the benefits may not pan out. But I'll look into anyway to see if the RUN commands do some caching in this case (I think it does but I'm not sure).
